name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6
    - run: julia -e '
            using Pkg;
            Pkg.add(["NodeJS", "PkgPage"]);
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js purgecss`);
            import PkgPage;
            PkgPage.optimize(input="page", output="")'
    - run: touch page/__site/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
          branch: gh-pages
          folder: page/__site
